### ISSUE TITLE
Updating to ember 2.12 I get a depreciation warning

### ISSUE THREAD

**Issue by kcincode** [arenoir/ember-cli-deploy-rsync#15]
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here:
  Object.<anonymous> (/Users/fellw9/Projects/almanac/frontend/node_modules/ember-cli-deploy-rsync/index.js:5:15)

**Comment by kcincode** [comment]
never mind, I see that it was fixed, its just not being pulled in via npm

**Comment by arenoir** [comment]
I pushed a new version to npm

**Comment by Prabhakar-Poudel** [comment]
Still not getting pulled via npm.
I still see the deprecation and when I check the node_modules/ old code persist.
